# Customise this file, documentation can be found here:
# https://github.com/fastlane/fastlane/tree/master/fastlane/docs
# All available actions: https://github.com/fastlane/fastlane/blob/master/fastlane/docs/Actions.md
# can also be listed using the `fastlane actions` command

# Change the syntax highlighting to Ruby
# All lines starting with a # are ignored when running `fastlane`

# If you want to automatically update fastlane if a new version is available:
# update_fastlane

# This is the minimum version number required.
# Update this, if you use features of a newer version
fastlane_version "1.81.0"

default_platform :ios

platform :ios do
  before_all do
  end

  desc "Submit a new Beta Build to Apple TestFlight"
  desc "This will also make sure the profile is up to date"
  lane :beta do
    ensure_git_status_clean

    changelog = prompt(text: "Changelog: ")

    increment_build_number
    commit_version_bump
    push_to_git_remote

    badge

    match(type: "appstore")
    gym(scheme: "Quakes") # Build your app - more options available

    pilot(changelog: changelog)

    reset_git_repo
  end

  desc "Deploy a new version to the App Store"
  lane :appstore do
    # match(type: "appstore")
    # snapshot
    gym(scheme: "Quakes") # Build your app - more options available
    deliver(force: true)
    # frameit
  end

  error do |lane, exception|
    notification(subtitle: "Fastlane Error", message: "Fastlane failed to finish lane '#{lane}' with error: '#{exception}'.")
  end
end